[[redirects]]
  from = "/api/*" # Redirige todas las solicitudes que comiencen con /api/
  to = "https://pleasant-blessing-production-1e47.up.railway.app/api/:splat" # Redirige al backend
  status = 200
  force = true

[[redirects]]
  from = "/auth/validatedToken/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*" # Aplica a todas las rutas
  [headers.values]
    Access-Control-Allow-Origin = "*" # Permite todas las solicitudes de cualquier origen (puedes especificar uno en lugar de '*')
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS" # Métodos permitidos
    Access-Control-Allow-Headers = "Origin, Content-Type, Accept, Authorization" # Encabezados permitidos